development:
  adapter: mysql2
  database: fairefortunedb
  username: root
  password: lavelle
  host: localhost
production:
  adapter: mysql2
  database: fairefortunedb
  username: root
  password: lavelle
  host: localhost
