# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4365973c95a72d01532f2ecfe2407029faf9546b438a42347a1f7f871709c0aa3f3a6c60276771f2183e5fd31f3b4aa70fcedadae4974f6bf8bf18320d4770

test:
  secret_key_base: 556975fa0a4c2311701669d713b2aad2a8d0ff6fe7f5d6cb6e92870bed5f569776733990f16b33ce2e9f00d5368b3bcc06482843a9b2883bf46c4b879c636567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
